Drop Table dbo.P_AXOrderInfo
Drop Table dbo.P_Materails
Drop Table dbo.P_Provider
Drop Table dbo.P_PurchInfo
Drop Table dbo.P_PurchInfoBak
Drop Table dbo.P_Transfer
Drop Table dbo.P_TransferBak
Drop Table dbo.P_WaiXieBak
Drop Table dbo.P_WaiXieInfo
Drop Table dbo.S_AXCardInfo
Drop Table dbo.S_Batcode
Drop Table dbo.S_Bill
Drop Table dbo.S_BillBak
Drop Table dbo.S_StockMatch
Drop Table dbo.S_Truck
Drop Table dbo.S_ZTLines
Drop Table dbo.S_ZTTrucks
Drop Table dbo.Sys_BaseInfo
Drop Table dbo.Sys_EventLog
Drop Table dbo.Sys_Picture
Drop Table dbo.Sys_PoundBak
Drop Table dbo.Sys_PoundLog
Drop Table dbo.Sys_SerialBase
Drop Table dbo.Sys_SerialStatus
Drop Table dbo.Sys_WeixinLog
Drop Table dbo.Sys_WeixinMatch
Drop Table dbo.Sys_WeixinTemplate