Delete From Sys_Dict Where D_Name='PackerItem'
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','袋包机_1#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','袋包机_2#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','袋包机_3#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','袋包机_4#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','袋包机_5#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','吨包机_1#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','吨包机_2#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_1#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_2#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_3#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_4#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_5#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_6#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_7#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','散包机_8#')
Insert into Sys_Dict(D_Name,D_Desc,D_Value) Values('PackerItem','包装机名称','熟料散装系统')