create nonclustered index idx_id on dbo.P_AXOrderInfo(C_ID desc,C_Stock)with(allow_page_locks=off)
create nonclustered index idx_card on dbo.P_PurchInfo(P_Card desc)
create nonclustered index idx_date on dbo.P_PurchInfo(P_Date)with(allow_page_locks=off)
create nonclustered index idx_id on dbo.P_PurchInfo(P_ID desc)
create nonclustered index idx_sync on dbo.P_PurchInfo(P_SyncDate,P_SyncNum,P_OutFact desc)
create nonclustered index idx_date on dbo.P_Transfer(T_Date)with(allow_page_locks=off)
create nonclustered index idx_id on dbo.P_Transfer(T_ID)with(allow_page_locks=off)
create nonclustered index idx_sync on dbo.P_Transfer(T_SyncDate,T_SyncNum)
create nonclustered index idx_card on dbo.P_WaiXieInfo(W_Card desc)with(allow_page_locks=off)
create nonclustered index idx_id on dbo.P_WaiXieInfo(W_ID desc)with(allow_page_locks=off)
create nonclustered index idx_sync on dbo.P_WaiXieInfo(W_SyncDate,W_SyncNum desc,W_OutFact2 desc)with(allow_page_locks=off)
create nonclustered index idx_id on dbo.S_AXCardInfo(C_ID,C_Stock)with(allow_page_locks=off)
create nonclustered index idx_card on dbo.S_Bill(L_Card desc)with(allow_page_locks=off)
create nonclustered index idx_customer on dbo.S_Bill(L_CusName,L_CusPY)with(allow_page_locks=off)
create nonclustered index idx_date on dbo.S_Bill(L_Date desc)with(allow_page_locks=off)
create nonclustered index idx_id on dbo.S_Bill(L_ID desc)
create nonclustered index idx_status on dbo.S_Bill(L_Status desc)with(allow_page_locks=off)
create nonclustered index idx_status_all on dbo.S_Bill(L_Status desc,L_NextStatus desc)with(allow_page_locks=off)
create nonclustered index idx_sync on dbo.S_Bill(L_SyncDate,L_SyncNum,L_OutFact desc)with(allow_page_locks=off)
create nonclustered index idx_truck on dbo.S_Bill(L_Truck)with(allow_page_locks=off)
create nonclustered index idx_bill on dbo.S_ZTTrucks(T_Bill)with(allow_page_locks=off)
create nonclustered index idx_truck on dbo.S_ZTTrucks(T_Truck)with(allow_page_locks=off)
create nonclustered index idx_query on dbo.Sys_EventLog(L_Date desc)with(allow_page_locks=off)
create nonclustered index idx_bill on dbo.Sys_PoundLog(P_Bill desc)with(allow_page_locks=off)
create nonclustered index idx_id on dbo.Sys_PoundLog(P_ID desc)with(allow_page_locks=off)
create nonclustered index idx_mdate on dbo.Sys_PoundLog(P_MDate desc)
create nonclustered index idx_pdate on dbo.Sys_PoundLog(P_PDate desc)
create nonclustered index idx_pmdate on dbo.Sys_PoundLog(P_PDate desc,P_MDate desc)with(allow_page_locks=off)
create nonclustered index idx_truck on dbo.Sys_PoundLog(P_Truck)with(allow_page_locks=off)
create nonclustered index idx_type on dbo.Sys_PoundLog(P_Type)with(allow_page_locks=off)