unit UAXService;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}
{$I LibFun.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf
  {$IFDEF RO_v90}, uROProxy{$ENDIF};

const
  { Library ID }
  LibraryUID = '{7E519127-6908-4C02-93C2-0FCDCBD33916}';
  WSDLLocation = 'http://10.9.1.97/CardTransToERP/WebService.asmx?WSDL';
  TargetNamespace = 'http://tempuri.org/';

  { Service Interface ID's }
  IWebService_IID : TGUID = '{47CC4D9D-75E6-4732-9577-3C5F6C2B7C66}';
  WebService_EndPointURI = 'http://10.9.1.97/CardTransToERP/WebService.asmx';

  { Event ID's }

type
  { Forward declarations }
  IWebService = interface;


  { IWebService }
  IWebService = interface
    ['{47CC4D9D-75E6-4732-9577-3C5F6C2B7C66}']
    function HelloWorld: WideString;
    function test: WideString;
    function GetSalesInfoByCustCard(const _xml: WideString): WideString;
    function GetPurchInfoByVendAccount(const _xml: WideString): WideString;
    function CheckPassByQtyAmount(const _xml: WideString): WideString;
    function SetSalesPackingSlip(const _xml: WideString): WideString;
    function SetPurchPackingSlip(const _xml: WideString): WideString;
    function SetOutSourceWeight(const _xml: WideString): WideString;
    function SetItemTransfer(const _xml: WideString): WideString;
    function GetProportionInfoByItemID(const _xml: WideString): WideString;
    function SetSalseReturn(const _xml: WideString): WideString;
    function SetPurchCorrection(const _xml: WideString): WideString;
    function SetSalesIssueCard(const _xml: WideString): WideString;
    function SetSalesFirstWeigh(const _xml: WideString): WideString;
    function GetCardStatus(const _xml: WideString): WideString;
    function SetSalesCardCancel(const _xml: WideString): WideString;
  end;

  { CoWebService }
  CoWebService = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IWebService;
  end;

  { TWebService_Proxy }
  TWebService_Proxy = class(TROProxy, IWebService)
  protected
    function __GetInterfaceName:string; override;

    function HelloWorld: WideString;
    function test: WideString;
    function GetSalesInfoByCustCard(const _xml: WideString): WideString;
    function GetPurchInfoByVendAccount(const _xml: WideString): WideString;
    function CheckPassByQtyAmount(const _xml: WideString): WideString;
    function SetSalesPackingSlip(const _xml: WideString): WideString;
    function SetPurchPackingSlip(const _xml: WideString): WideString;
    function SetOutSourceWeight(const _xml: WideString): WideString;
    function SetItemTransfer(const _xml: WideString): WideString;
    function GetProportionInfoByItemID(const _xml: WideString): WideString;
    function SetSalseReturn(const _xml: WideString): WideString;
    function SetPurchCorrection(const _xml: WideString): WideString;
    function SetSalesIssueCard(const _xml: WideString): WideString;
    function SetSalesFirstWeigh(const _xml: WideString): WideString;
    function GetCardStatus(const _xml: WideString): WideString;
    function SetSalesCardCancel(const _xml: WideString): WideString;
  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoWebService }

class function CoWebService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IWebService;
begin
  result := TWebService_Proxy.Create(aMessage, aTransportChannel);
end;

{ TWebService_Proxy }

function TWebService_Proxy.__GetInterfaceName:string;
begin
  result := 'WebService';
end;

function TWebService_Proxy.HelloWorld: WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/HelloWorld', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'HelloWorld', 'HelloWorldResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'HelloWorld');
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('HelloWorldResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.test: WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/test', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'test', 'testResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'test');
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('testResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.GetSalesInfoByCustCard(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/GetSalesInfoByCustCard', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'GetSalesInfoByCustCard', 'GetSalesInfoByCustCardResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'GetSalesInfoByCustCard');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('GetSalesInfoByCustCardResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.GetPurchInfoByVendAccount(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/GetPurchInfoByVendAccount', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'GetPurchInfoByVendAccount', 'GetPurchInfoByVendAccountResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'GetPurchInfoByVendAccount');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('GetPurchInfoByVendAccountResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.CheckPassByQtyAmount(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/CheckPassByQtyAmount', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'CheckPassByQtyAmount', 'CheckPassByQtyAmountResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'CheckPassByQtyAmount');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('CheckPassByQtyAmountResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetSalesPackingSlip(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetSalesPackingSlip', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetSalesPackingSlip', 'SetSalesPackingSlipResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetSalesPackingSlip');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetSalesPackingSlipResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetPurchPackingSlip(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetPurchPackingSlip', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetPurchPackingSlip', 'SetPurchPackingSlipResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetPurchPackingSlip');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetPurchPackingSlipResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetOutSourceWeight(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetOutSourceWeight', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetOutSourceWeight', 'SetOutSourceWeightResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetOutSourceWeight');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetOutSourceWeightResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetItemTransfer(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetItemTransfer', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetItemTransfer', 'SetItemTransferResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetItemTransfer');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetItemTransferResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.GetProportionInfoByItemID(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/GetProportionInfoByItemID', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'GetProportionInfoByItemID', 'GetProportionInfoByItemIDResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'GetProportionInfoByItemID');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('GetProportionInfoByItemIDResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetSalseReturn(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetSalseReturn', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetSalseReturn', 'SetSalseReturnResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetSalseReturn');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetSalseReturnResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetPurchCorrection(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetPurchCorrection', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetPurchCorrection', 'SetPurchCorrectionResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetPurchCorrection');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetPurchCorrectionResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetSalesIssueCard(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetSalesIssueCard', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetSalesIssueCard', 'SetSalesIssueCardResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetSalesIssueCard');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetSalesIssueCardResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetSalesFirstWeigh(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetSalesFirstWeigh', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetSalesFirstWeigh', 'SetSalesFirstWeighResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetSalesFirstWeigh');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetSalesFirstWeighResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.GetCardStatus(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/GetCardStatus', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'GetCardStatus', 'GetCardStatusResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'GetCardStatus');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('GetCardStatusResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TWebService_Proxy.SetSalesCardCancel(const _xml: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['Action', 'Location', 'remap_CheckPassByQtyAmount', 'remap_GetCardStatus', 'remap_GetProportionInfoByItemID', 'remap_GetPurchInfoByVendAccount', 'remap_GetSalesInfoByCustCard'
      , 'remap_HelloWorld', 'remap_SetItemTransfer', 'remap_SetOutSourceWeight', 'remap_SetPurchCorrection', 'remap_SetPurchPackingSlip', 'remap_SetSalesCardCancel', 'remap_SetSalesFirstWeigh', 'remap_SetSalesIssueCard'
      , 'remap_SetSalesPackingSlip', 'remap_SetSalseReturn', 'remap_test', 'SOAPInputNameOverride', 'SOAPOutputNameOverride', 'Style', 'TargetNamespace', 'Type'
      , 'Use', 'Wsdl'], 
      ['http://tempuri.org/SetSalesCardCancel', 'http://10.9.1.97/CardTransToERP/WebService.asmx', 'http://tempuri.org/CheckPassByQtyAmount', 'http://tempuri.org/GetCardStatus', 'http://tempuri.org/GetProportionInfoByItemID', 'http://tempuri.org/GetPurchInfoByVendAccount', 'http://tempuri.org/GetSalesInfoByCustCard'
      , 'http://tempuri.org/HelloWorld', 'http://tempuri.org/SetItemTransfer', 'http://tempuri.org/SetOutSourceWeight', 'http://tempuri.org/SetPurchCorrection', 'http://tempuri.org/SetPurchPackingSlip', 'http://tempuri.org/SetSalesCardCancel', 'http://tempuri.org/SetSalesFirstWeigh', 'http://tempuri.org/SetSalesIssueCard'
      , 'http://tempuri.org/SetSalesPackingSlip', 'http://tempuri.org/SetSalseReturn', 'http://tempuri.org/test', 'SetSalesCardCancel', 'SetSalesCardCancelResponse', 'document', TargetNamespace, 'SOAP'
      , 'literal', WSDLLocation]);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NewLibrary', __InterfaceName, 'SetSalesCardCancel');
    __Message.Write('_xml', TypeInfo(WideString), _xml, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('SetSalesCardCancelResult', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

initialization
  RegisterProxyClass(IWebService_IID, TWebService_Proxy);


finalization
  UnregisterProxyClass(IWebService_IID);

end.
